### ISSUE TITLE
Map zip to fips and include in response

### ISSUE THREAD

**Issue by tiffehr** [newsdev/geoip#16]
Via @gka in Slack: 
> [17:14]  *gregoraisch* hey, what do you think how hard it would be to add county fips to the geoip response json? saw that there’s already a zip code

**Comment by gka** [comment]
the way we have been doing this in previous projects was looking up the lat/lon coordinate in a map and use the attributes of the county polygon that happens to be at that point.

this approach basically works but there are downsides.

for one, the topojson we're loading in is pretty big (~2mb w/o gzip). this is not a big issue on desktop where we have to load this file anyway to render the map, but it is an issue on mobile where we are using static pre-rendered maps.

the other issue is that there are messy cases where the coordinate is on a lake or river so no polygon is found (though this is very rare I guess).

so it would be nice to get the fips code as part of the result.

**Comment by tiffehr** [comment]
@gka Something like this would work?  https://github.com/kavanagh/zipcodes

I can't find a node version that's not overblown, so maybe I'll just do this myself.

**Comment by gka** [comment]
well, yes, but ideally I wouldn't have to do another request but get the fips code with the first geoip response. only for us, of course

**Comment by tiffehr** [comment]
No, you wouldn't need to.  We'd do that lookup with the first geoip response.  I was mostly documenting what could be running at that step, not a second XHR.

**Comment by gka** [comment]
ah, got it. nice

**Comment by tiffehr** [comment]
Incorporating `city_fip`, `county_fip` and the combo of the two, `geoid_fip` from the [datasource](https://github.com/newsdev/geoip/commit/e9e49983c5ca0e744583717cfdbce3fd7b14acbf) I manually added and cleaned up.

E.g. `{"response":true,"data":{"country_code":"US","country_code3":"USA","country_name":"United States","region":"NY","city":"New York","postal_code":"10018","latitude":40.75529861450195,"longitude":-73.99240112304688,"metro_code":501,"dma_code":501,"area_code":212,"continent_code":"NA","time_zone":"America/New_York","zone_abbr":"ET","city_fip":"36","county_fip":"061","geoid_fip":"36061","intranet":false},"status":"ok"}`
