### ISSUE TITLE
Mark intranet/extranet as a class

### ISSUE THREAD

**Issue by tiffehr** [newsdev/geoip#18]
Result: `html.geo-office-internal` and `html.geo-office-nyhq` / `html.geo-office-dc`....

**Comment by bkoski** [comment]
One point here: so long as this repo is public, we probably should provide the IP range as a an `ENV` config.

I suppose this would have to be some kind of JSON object.  Perhaps we could pass a `{ cird : label }` object and then use something like https://github.com/skx/cidr_match.js to evaluate?

The config could look something like this:

```json
{ "170.149.0.0/24" : "office-1", "92.92.92.92/32" : "office-2" }
```

**Comment by tiffehr** [comment]
Abandoned.  Not really needed at this time.
