### ISSUE TITLE
Add Airbrake support for better monitoring of service crashes

### ISSUE THREAD

**Issue by tiffehr** [newsdev/geoip#27]
- [x] add Airbrake https://github.com/newsdev/geoip/pull/25/commits/7f33402de9baeb4ac93b787b4895e47c0e46c7bc
- [x] verify

**Comment by bkoski** [comment]
We should pass through the token as `process.env.AIRBRAKE_API_KEY`

**Comment by tiffehr** [comment]
`process.env.AIRBRAKE_API_KEY`, `process.env.AIRBRAKE_PROJECT_ID` and `NODE_ENV=production` all passed as ENV variables.
