### ISSUE TITLE
callback is not invoked for international readers

### ISSUE THREAD

**Issue by bkoski** [newsdev/geoip#30]
@isaacwhite and I ran into this when investigating https://github.com/newsdev/google-travel-feeds/issues/13 -- the optional `callback` is consistently invoked for US users, but was not firing for international visitors.

The problem seems to lie in this line:
https://github.com/newsdev/geoip/blob/master/frontend/geoip.js#L96

The international locations do not have a `dma_code` and sometimes do not have a `postal_code`.  The early return in this line causes `decorate()` to bail before it's had a chance to invoke the callback.

**Comment by tiffehr** [comment]
Good catch!  I'll fix it soon.
